export const LOGIN_VIA_OTP = "Login via OTP";
export const LOADING_CHAT = "Loading Chat...";
export const HOME_TITLE = "Meet Gemini Clone,"
export const HOME_TITLE2 = "your personal AI assistant";
export const APP_NAME = "Gemini Clone";
export const SIGN_IN = "Sign in";
export const OTP_SENT = "OTP sent! (simulated)"
export const OTP_SUCCESS = "OTP verified successfully!";
export const OTP_ERROR = "Invalid OTP, please try again.";
export const START_NEW_CHAT = "Start New Chat";
export const CHAT_PLACEHOLDER = "No messages yet!";
export const OTP_STEP_SEND = "send";
export const OTP_STEP_VERIFY = "verify";
export const OTP_ERR_COUNTRY_CODE = "Select country code";
export const OTP_ERR_TOO_SHORT = "Too short";
export const OTP_ERR_TOO_LONG = "Too long";
export const OTP_ERR_NUMBERS_ONLY = "Numbers only";
export const OTP_ERR_6_DIGIT = "Enter 6‑digit OTP when verifying";